name: Docker Build & Push rpi Image
on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-18.04
    env:
      DOCKER_REGISTRY: quay.io
      DOCKER_IMAGE: zemiak/movies-update
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      DOCKER_TARGET_PLATFORM: linux/amd64
    steps:
    - name: Checkout the code
      uses: actions/checkout@v1
    - name: Set up JDK 1.11
      uses: actions/setup-java@v1
      with:
        java-version: 1.11
    - name: Package
      run: mvn package -DskipTests -Dmaven.test.skip=true --file pom.xml
    - name: Set up Docker Buildx
      uses: crazy-max/ghaction-docker-buildx@v1
      with:
        buildx-version: latest
    - name: Prepare
      if: success()
      id: prepare
      run: |
        echo ::set-output name=docker_platform::${DOCKER_TARGET_PLATFORM}
        echo ::set-output name=docker_image::${DOCKER_REGISTRY}/${DOCKER_IMAGE}
        echo ::set-output name=version::${GITHUB_RUN_NUMBER}
    - name: Docker Login
      if: success()
      run: |
        echo "${DOCKER_PASSWORD}" | docker login ${DOCKER_REGISTRY} --username "${DOCKER_USERNAME}" --password-stdin
    - name: Run Buildx (push image)
      if: success()
      run: |
        docker buildx build \
                --platform ${{ steps.prepare.outputs.docker_platform }} \
                --tag ${{ steps.prepare.outputs.docker_image }}:latest \
                --file ./src/main/docker/Dockerfile.fast-jar \
                --output type=image,push=true .
