name: Java 11 Tests

on:
  push:
    branches:
      - master
      - develop
 
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.11
      uses: actions/setup-java@v1
      with:
        java-version: 1.11
    - name: Run tests
      run: mvn test --file pom.xml
